export default [
    {
      id: 1,
      company: "Netflix",
      date: "27 March 2020",
      time: "12:30 PM",
      amount: -2500,
      status: "debit",
      transactionType: "expense", // فلوس مخصومة
      icon: "ArrowDown",
      color: "red",
    },
    {
      id: 2,
      company: "Apple",
      date: "27 March 2020",
      time: "12:30 PM",
      amount: 2500,
      status: "credit",
      transactionType: "income", // فلوس جاية
      icon: "ArrowUp",
      color: "green",
    },
    {
      id: 3,
      company: "Stripe",
      date: "26 March 2020",
      time: "13:45 PM",
      amount: 800,
      status: "credit",
      transactionType: "income",
      icon: "ArrowUp",
      color: "green",
    },
    {
      id: 4,
      company: "HubSpot",
      date: "26 March 2020",
      time: "12:30 PM",
      amount: 1700,
      status: "credit",
      transactionType: "income",
      icon: "ArrowUp",
      color: "green",
    },
    {
      id: 5,
      company: "Webflow",
      date: "26 March 2020",
      time: "05:00 AM",
      amount: null,
      status: "pending",
      transactionType: "pending", // pending
      icon: "AlertCircle",
      color: "gray",
    },
    {
      id: 6,
      company: "Microsoft",
      date: "25 March 2020",
      time: "16:30 PM",
      amount: -987,
      status: "debit",
      transactionType: "expense",
      icon: "ArrowDown",
      color: "red",
    },
  ];
  